[package]
name = "bandersnatch"
version = "0.1.1"
edition = "2021"

[dependencies]
ark-vrf = { version = "0.1.1", features = ["bandersnatch", "ring"] }
hex = "0.4.3"
libc = "0.2.161"

[lib]
crate-type = ["cdylib"]
